node {

	def app

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/manikandansv/microservice-poc.git', credentialsId: 'microservice-poc', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Build Image') {
            dir ('gateway-service') {
                app = docker.build "manisv/microservice-poc-gateway-service:${env.version}"
            }
        }
        
         stage('Push Image') {
        	print 'Push Image'
            		docker.withRegistry('https://registry.hub.docker.com','DockerHub'){
            		    app.push()
            		} 	
        }

//        stage ('Run') {
//            docker.image("localhost:5000/gateway-service:${env.version}").run('-p 3333:3333 -h gateway --name gateway --link discovery --link account --link customer')
//        }
     

    }

}