server:  
  port: ${appPort:8761}
    
management:
   contextPath: /admin
    
eureka:  
  environment: ${environment}
  datacenter: ${dataCenter}
  enableSelfPreservation: false 
  instance:
    hostname: ${hostName}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
       defaultZone: ${peerUrls}      
    
---
spring:
  profiles: standalone
hostName: localhost
environment: local
dataCenter: ${hostName}
peerUrls: http://localhost:${server.port}/eureka/

---
spring:
  profiles: peerAware