node {

	def app

    withMaven(maven:'maven') {
    
    	print 'Inside Discovery-Service Jenkins File'

        stage('Checkout') {
            git url: 'https://github.com/manikandansv/microservice-poc.git', credentialsId: 'microservice-poc', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Build Image') {
        	print 'Build Image'
            dir ('microservice-poc-discovery-service') {
                sh 'docker build -t "manisv/microservice-poc-discovery-service:${env.version}" .'
                //app.push()
            }
        }
        
        stage('Push Image') {
            steps {
        		   withDockerRegistry([ credentialsId: "6544de7e-17a4-4576-9b9b-e86bc1e4f903", url: "" ]) {
         			 sh 'docker push manisv/microservice-poc-discovery-service:${env.version}'
       			 }
       		}
        }

//
//        stage ('Run') {
//            docker.image("localhost:5000/discovery-service:${env.version}").run('-p 8761:8761 -h discovery --name discovery')
//        }
//
//        stage ('Final') {
//            build job: 'account-service-pipeline', wait: false
//        }      
	}

}