node {

	def app
	def ecrApp

    withMaven(maven:'maven') {
    
    	print 'Inside Discovery-Service Jenkins File'

        stage('Checkout') {
            git url: 'https://github.com/manikandansv/microservice-poc.git', credentialsId: 'microservice-poc', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Build Image') {
        	print 'Build Image'
            dir ('microservice-poc-discovery-service') {
            	app = docker.build "manisv/microservice-poc-discovery-service:${env.version}"
            	ecrApp = docker.build "microservice-poc-discovery-service:${env.version}"
            }
        }
        
        stage('Push Image') {
        	print 'Push Image'
            		docker.withRegistry('https://registry.hub.docker.com','DockerHub'){
            		    app.push()
            		}
            		docker.withRegistry('https://335191158991.dkr.ecr.ap-south-1.amazonaws.com','ecr:ap-south-1:aws-ecr'){
            		    ecrApp.push();
            		}

       	
        }

//
//        stage ('Run') {
//            docker.image("localhost:5000/discovery-service:${env.version}").run('-p 8761:8761 -h discovery --name discovery')
//        }
//
//        stage ('Final') {
//            build job: 'account-service-pipeline', wait: false
//        }      
	}

}