FROM openjdk
MAINTAINER Manikandan s.v.manikandan@gmail.com
ADD target/microservice-poc-customer-service.jar microservice-poc-customer-service.jar
ENTRYPOINT ["java", "-jar", "/microservice-poc-customer-service.jar"]
EXPOSE 3333