FROM openjdk
MAINTAINER Manikandan s.v.manikandan@gmail.com
ADD target/microservice-poc-account-service.jar microservice-poc-account-service.jar
ENTRYPOINT ["java", "-jar", "/microservice-poc-account-service.jar"]
EXPOSE 2222